### ISSUE TITLE
Supergun pinout risk.

### ISSUE THREAD

**Issue by Dubon77** [bootsector/LLOAD#1]
Currently connecting a controller that is wired for connecting to a supergun can not be directly connected to the db15 port and requires an adapter. Neo geo controllers should be fine. This is , afaik, because pin 10 currently is powered and pressing a button connected to it could cause damage to the arduino. Because of this either an adapter, or a revision of the main pcb witch fixes this is required.

**Comment by bootsector** [comment]
Pushed new v1.1 revision. This is still not compatible with Supergun (although it still works with Neo Geo and Neo Geo CD pads, just like the previous version). I will work on a PCB adapter to allow supergun on this soon.
