### ISSUE TITLE
Shoulder buttons (L and R) inputs are not detected on genuine Sega Saturn controllers.

### ISSUE THREAD

**Issue by mathieulh** [bootsector/LLOAD#2]
Shoulder buttons (L and R) inputs are not detected on genuine Sega Saturn controllers.

This happens even over usb, L and R inputs are not registered at all, I have tested this with 2 different Official, Sega manufactured Saturn controllers.

**Comment by bootsector** [comment]
That's strange. It works here when, for example, plugging LLOAD to a Windows based PC then checking those buttons with joy.cpl. What's your test scenario here?

**Comment by mathieulh** [comment]
I am simply trying to map the saturn controller on MiSTer using the OSD and the L and R buttons are not recognized unless I push both at once, same thing occurs on joy.cpl
Button number 7 lights up when I push both L and R, none light up when I push them separately on joy.cpl

**Comment by bootsector** [comment]
Found the issue. There's some uncommitted code here that took care of that. I will push the fix soon!

**Comment by bootsector** [comment]
Commit d2a1b20 should take care of this. Please let me know if it didn't. Thanks!

**Comment by mathieulh** [comment]
I tested the commit, the issue is fixed.
